/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateEmpresaArgs } from "./CreateEmpresaArgs";
import { UpdateEmpresaArgs } from "./UpdateEmpresaArgs";
import { DeleteEmpresaArgs } from "./DeleteEmpresaArgs";
import { EmpresaFindManyArgs } from "./EmpresaFindManyArgs";
import { EmpresaFindUniqueArgs } from "./EmpresaFindUniqueArgs";
import { Empresa } from "./Empresa";
import { EmpresaService } from "../empresa.service";

@graphql.Resolver(() => Empresa)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EmpresaResolverBase {
  constructor(
    protected readonly service: EmpresaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Empresa",
    action: "read",
    possession: "any",
  })
  async _empresasMeta(
    @graphql.Args() args: EmpresaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Empresa])
  @nestAccessControl.UseRoles({
    resource: "Empresa",
    action: "read",
    possession: "any",
  })
  async empresas(
    @graphql.Args() args: EmpresaFindManyArgs
  ): Promise<Empresa[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Empresa, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Empresa",
    action: "read",
    possession: "own",
  })
  async empresa(
    @graphql.Args() args: EmpresaFindUniqueArgs
  ): Promise<Empresa | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Empresa)
  @nestAccessControl.UseRoles({
    resource: "Empresa",
    action: "create",
    possession: "any",
  })
  async createEmpresa(
    @graphql.Args() args: CreateEmpresaArgs
  ): Promise<Empresa> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Empresa)
  @nestAccessControl.UseRoles({
    resource: "Empresa",
    action: "update",
    possession: "any",
  })
  async updateEmpresa(
    @graphql.Args() args: UpdateEmpresaArgs
  ): Promise<Empresa | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Empresa)
  @nestAccessControl.UseRoles({
    resource: "Empresa",
    action: "delete",
    possession: "any",
  })
  async deleteEmpresa(
    @graphql.Args() args: DeleteEmpresaArgs
  ): Promise<Empresa | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
